# Generated by Django 4.2.25 on 2025-10-16 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='diet_type',
            field=models.CharField(max_length=24, null=True),
        ),
    ]
