# Generated by Django 4.2.25 on 2025-10-16 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_diet_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='diet_type',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
    ]
