# Generated by Django 4.2.27 on 2025-12-11 21:48

from django.db import migrations, connection


def rename_table_if_needed(apps, schema_editor):
    """Rename api_user to users only if api_user exists and users doesn't"""
    with connection.cursor() as cursor:
        # Check if api_user exists
        cursor.execute("""
            SELECT EXISTS (
                SELECT FROM information_schema.tables 
                WHERE table_schema = 'public' 
                AND table_name = 'api_user'
            );
        """)
        api_user_exists = cursor.fetchone()[0]
        
        # Check if users already exists
        cursor.execute("""
            SELECT EXISTS (
                SELECT FROM information_schema.tables 
                WHERE table_schema = 'public' 
                AND table_name = 'users'
            );
        """)
        users_exists = cursor.fetchone()[0]
        
        # Only rename if api_user exists and users doesn't
        if api_user_exists and not users_exists:
            cursor.execute('ALTER TABLE api_user RENAME TO users;')


def reverse_rename_table(apps, schema_editor):
    """Reverse: rename users back to api_user if users exists and api_user doesn't"""
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT EXISTS (
                SELECT FROM information_schema.tables 
                WHERE table_schema = 'public' 
                AND table_name = 'users'
            );
        """)
        users_exists = cursor.fetchone()[0]
        
        cursor.execute("""
            SELECT EXISTS (
                SELECT FROM information_schema.tables 
                WHERE table_schema = 'public' 
                AND table_name = 'api_user'
            );
        """)
        api_user_exists = cursor.fetchone()[0]
        
        if users_exists and not api_user_exists:
            cursor.execute('ALTER TABLE users RENAME TO api_user;')


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_diet_type'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    rename_table_if_needed,
                    reverse_rename_table,
                ),
            ],
            state_operations=[
                migrations.AlterModelTable(
                    name='user',
                    table='users',
                ),
            ],
        ),
    ]
