# Generated by Django 4.2.27 on 2025-12-11 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_diet_type'),
    ]

    operations = [
        migrations.RunSQL(
            sql='ALTER TABLE api_user RENAME TO users;',
            reverse_sql='ALTER TABLE users RENAME TO api_user;',
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
