# Generated by Django 4.2.27 on 2025-12-11 21:58

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20251211_2156'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='triedrecipe',
            options={'ordering': ['-date_added'], 'verbose_name': 'Tried Recipe', 'verbose_name_plural': 'Tried Recipes'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='diet_type',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=70, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=24, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='triedrecipe',
            unique_together={('tried_by', 'recipe_id')},
        ),
        migrations.AlterModelTable(
            name='triedrecipe',
            table='tried_recipes',
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('daily_calorie_goal', models.SmallIntegerField(null=True)),
                ('daily_protein_goal', models.SmallIntegerField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('bio', models.CharField(blank=True, default='', max_length=500)),
                ('diet_type', models.JSONField(blank=True, default=dict)),
                ('profile_picture', models.URLField(blank=True, default='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'db_table': 'user_profiles',
            },
        ),
    ]
