# Generated by Django 5.2.12 on 2026-03-30 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipes', '0005_fix_recipe_field_lengths'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeNutrition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calories', models.DecimalField(decimal_places=2, max_digits=8)),
                ('protein', models.DecimalField(decimal_places=2, max_digits=8)),
                ('carbs', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fat', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fiber', models.DecimalField(decimal_places=2, max_digits=8)),
                ('sugar', models.DecimalField(decimal_places=2, max_digits=8)),
                ('sodium', models.DecimalField(decimal_places=2, max_digits=8)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('recipe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition', to='recipes.recipe')),
            ],
            options={
                'verbose_name': 'Recipe Nutrition',
                'verbose_name_plural': 'Recipe Nutritions',
                'db_table': 'recipe_nutrition',
            },
        ),
    ]
