# Generated by Django 5.2.10 on 2026-01-30 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=24, unique=True)),
                ('calories_per_100g', models.FloatField()),
                ('protein_per_100g', models.FloatField()),
                ('carbs_per_100g', models.FloatField()),
                ('fat_per_100g', models.FloatField()),
                ('fiber_per_100g', models.FloatField()),
                ('sugar_per_100g', models.FloatField()),
                ('sodium_per_100g', models.FloatField()),
                ('default_unit', models.CharField(default='g', max_length=20)),
            ],
            options={
                'verbose_name': 'Ingredient',
                'verbose_name_plural': 'Ingredients',
                'db_table': 'ingredient',
            },
        ),
    ]
