# Generated by Django 5.2.12 on 2026-04-06 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0003_alter_ingredient_sodium_per_100g'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='calories_per_100g',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='carbs_per_100g',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='fat_per_100g',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='fiber_per_100g',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='protein_per_100g',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='sugar_per_100g',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
