--
-- PostgreSQL database dump
--

-- Dumped from database version 17.6
-- Dumped by pg_dump version 17.2

-- Started on 2026-03-16 22:14:51

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 80 (class 2615 OID 2200)
-- Name: public; Type: SCHEMA; Schema: -; Owner: pg_database_owner
--

CREATE SCHEMA public;


ALTER SCHEMA public OWNER TO pg_database_owner;

--
-- TOC entry 3733 (class 0 OID 0)
-- Dependencies: 80
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: pg_database_owner
--

COMMENT ON SCHEMA public IS 'standard public schema';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 334 (class 1259 OID 17493)
-- Name: Ingredient; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Ingredient" (
    id_pk bigint NOT NULL,
    name character varying NOT NULL,
    calories real,
    protein real,
    carbs real,
    fat real,
    fiber real,
    sugar real,
    sodium real
);


ALTER TABLE public."Ingredient" OWNER TO postgres;

--
-- TOC entry 335 (class 1259 OID 17496)
-- Name: Ingredient_id_pk_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Ingredient" ALTER COLUMN id_pk ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Ingredient_id_pk_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 333 (class 1259 OID 17485)
-- Name: recipe; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.recipe (
    id_pk bigint NOT NULL,
    public_id uuid,
    name character varying(50),
    date_created timestamp without time zone,
    instructions text,
    description text,
    date_updated timestamp without time zone,
    cuisine_type character varying(50),
    dietary_tags character varying(50)[],
    recipe_image text
);


ALTER TABLE public.recipe OWNER TO postgres;

--
-- TOC entry 3726 (class 0 OID 17493)
-- Dependencies: 334
-- Data for Name: Ingredient; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Ingredient" (id_pk, name, calories, protein, carbs, fat, fiber, sugar, sodium) FROM stdin;
1	GroundBeef	250	26	0	15	0	0	72
2	Chicken	239	27	0	14	0	0	74
3	Turkey	189	29	0	7	0	0	82
4	Ham	145	18	1.5	5	0	1	1200
5	MahiMahi	130	20	0	5	0	0	90
6	Salmon	208	20	0	13	0	0	59
7	Tuna	130	30	0	1	0	0	37
8	Shrimp	99	24	0	0.3	0	0	111
9	Egg	155	13	1.1	11	0	0.6	124
11	Tofu	76	8	2	5	0.3	0.6	14
12	Chickpeas	364	19	61	6	17.4	11	24
13	Lentils	353	25	60	1	10.7	2	6
14	CottageCheese	98	11	3.4	4.3	0	2.7	364
15	Cheese	402	25	1.3	33	0	0.5	621
16	Parmesan	431	36	4.1	26	0	0.9	1529
17	CreamCheese	342	6	4	34	0	3.2	321
18	Rice	130	7	28	0.3	0.6	0.1	2
19	Pasta	371	13	71	1.5	3.2	2.7	6
20	Bread	265	9	49	3.2	2.7	5	491
21	Tortilla	298	8	48	5	2.9	2	680
22	Oats	389	17	66	7	10.6	1	2
23	Noodles	138	9	25	0.5	1.2	1	5
24	Quinoa	368	14	64	6	7	3	5
25	SweetPotato	86	1.6	20	0.1	3	4.2	55
26	Oil	884	0	0	100	0	0	0
27	OliveOil	884	0	0	100	0	0	2
28	Butter	717	0.9	0.1	81	0	0.1	643
29	Mayo	680	1	0.6	75	0	0.4	635
30	Mustard	60	4	7	4	3.3	3	1100
31	Hummus	166	8	14	10	6	0.3	379
32	Peanut Butter	588	25	20	50	6	9	426
33	Avocado	160	2	9	15	6.7	0.7	7
34	Walnuts	654	15	14	65	6.7	2.6	2
35	AlmondMilk	17	0.4	0.6	1.1	0.2	0	59
36	CoconutMilk	230	2.3	6	24	2.2	3.3	15
37	Cream	345	2.1	3.4	37	0	2.8	38
38	Lettuce	15	1.4	2.9	0.2	1.3	0.8	28
39	Tomato	18	0.9	3.9	0.2	1.2	2.6	5
40	Cucumber	15	0.7	3.6	0.1	0.5	1.7	2
41	Onion	40	1.1	9.3	0.1	1.7	4.2	4
42	Pepper	31	1	6	0.3	2.1	4.2	4
43	BellPepper	31	1	6	0.3	2.1	4.2	4
44	Broccoli	34	2.8	7	0.4	2.6	1.7	33
45	Zucchini	17	1.2	3.1	0.3	1	2.5	8
46	Eggplant	25	1	6	0.2	3	3.5	2
47	Spinach	23	2.9	3.6	0.4	2.2	0.4	79
48	Carrot	41	0.9	10	0.2	2.8	4.7	69
49	Cabbage	25	1.3	5.8	0.1	2.5	3.2	18
50	Celery	14	0.7	3	0.2	1.6	1.3	80
51	Vegetables	30	1.5	5	0.2	2.5	2	30
52	Mushroom	22	3.1	3.3	0.3	1	2	5
53	Apple	52	0.3	14	0.2	2.4	10	1
54	Banana	89	1.1	23	0.3	2.6	12	1
55	Lemon	29	1.1	9	0.3	2.8	2.5	2
56	Lime	30	0.7	11	0.2	2.8	1.7	2
57	Berries	57	1	12	0.5	6.5	5	1
58	Salt	0	0	0	0	0	0	38758
59	Garlic	149	6.4	33	0.5	2.1	1	17
60	Basil	23	3.2	2.7	0.6	1.6	0.3	4
61	Dill	43	3.5	7	1.1	2.1	0	61
62	Cinnamon	247	4	81	1.2	53.1	2.2	10
63	Vanilla	288	0.1	13	0.1	0	13	9
64	SoySauce	446	36	30	20	0.81	7	5493
65	Vinegar	18	0	0.9	0	0	0.4	5
66	SesameSeeds	573	18	23	50	11.8	0.3	11
67	Honey	304	0.3	82	0	0	82	4
68	Maple	260	0	67	0.2	0	60	12
69	Chia	486	17	42	31	34.4	0	16
70	AlmondFlour	571	21	22	53	10.4	4	1
71	BakingPowder	53	0	28	0	0	0	10600
72	Ice	0	0	0	0	0	0	0
\.


--
-- TOC entry 3725 (class 0 OID 17485)
-- Dependencies: 333
-- Data for Name: recipe; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.recipe (id_pk, public_id, name, date_created, instructions, description, date_updated, cuisine_type, dietary_tags, recipe_image) FROM stdin;
1	95cdd621-c803-4b5b-a8fb-4e4fbd6a57e5	Beef Stirfry	2026-01-18 00:00:00	\N	Meal: Lunch; Prep time: 60 min	2026-01-18 00:00:00	Chinese	{Regular,Lunch}	https://lifeloveandgoodfood.com/wp-content/uploads/2022/06/Pepper-Steak-Stir-Fry-2-1200x1200-1.jpg
2	621a296d-ae5f-40bf-8bbb-91703ba08e77	Chicken and Chickpea Salad	2026-01-18 00:00:00	\N	Meal: Lunch; Prep time: 60 min	2026-01-18 00:00:00	American	{Regular,Lunch}	https://static01.nyt.com/images/2024/01/10/multimedia/nb-chicken-and-chickpea-salad-kglm/nb-chicken-and-chickpea-salad-kglm-mediumSquareAt3X.jpg
3	5557ac11-e4ac-417a-9a5c-983a8b701e6b	Chicken Pasta	2026-01-18 00:00:00	\N	Meal: Lunch; Prep time: 45 min	2026-01-18 00:00:00	Italian	{Regular,Lunch}	https://www.wenthere8this.com/wp-content/uploads/2023/05/spicy-chicken-pasta-7.jpg
4	04f13c6a-9259-4930-b3e5-5e84e1cbe5e4	Grilled Chicken Salad	2026-01-18 00:00:00	\N	Meal: Lunch; Prep time: 60 min	2026-01-18 00:00:00	American	{Regular,Lunch}	https://assets.epicurious.com/photos/64a845e67799ee8651e4fb8f/16:9/w_6179,h_3476,c_limit/AshaGrilledChickenSalad_RECIPE_070523_56498.jpg
5	43dd876a-6826-45c2-ab69-6cc4a425831b	Turkey Wrap	2026-01-18 00:00:00	\N	Meal: Lunch; Prep time: 20 min	2026-01-18 00:00:00	American	{Regular,Lunch}	https://www.spendwithpennies.com/wp-content/uploads/2020/06/Turkey-Wrap-SpendWithPennies-4.jpg
6	802040b3-1022-449b-9145-61833e2b0510	Chicken Rice Bow	2026-01-18 00:00:00	\N	Meal: Dinner; Prep time: 60 min	2026-01-18 00:00:00	Asian Fusion	{Regular,Dinner}	https://inquiringchef.com/wp-content/uploads/2022/10/Gochujang-Chicken-Rice-Bowls_square-0189.jpg
7	8b9a668d-d434-4672-a628-e058add68ee7	Turkey Rice	2026-01-18 00:00:00	\N	Meal: Dinner; Prep time: 60 min	2026-01-18 00:00:00	International	{Regular,Dinner}	https://assets.epicurious.com/photos/5f99a933eb27e3e71e94ddc7/1:1/w_2849,h_2849,c_limit/TaiwaneseTurkeyRice_RECIPE_101920_1294_VOG_final.jpg
8	0a61e42e-543b-420d-964f-c8629a8e450c	Ham and Cheese Sandwich	2026-01-18 00:00:00	\N	Meal: Breakfast; Prep time: 20 min	2026-01-18 00:00:00	American	{Regular,Breakfast}	\N
9	441c1d74-6465-403c-941a-3ce8ea958c2e	Creamy Chicken Broccoli	2026-01-18 00:00:00	\N	Meal: Lunch; Prep time: 60 min	2026-01-18 00:00:00	International	{Regular,"Keto, Lunch"}	\N
10	28e9655b-f458-4dd8-a15e-a122b017b9e7	Grilled Steak	2026-01-18 00:00:00	\N	Meal: Lunch; Prep time: 45 min	2026-01-18 00:00:00	American	{Regular,"Keto, Lunch"}	\N
11	837e9770-7f76-457a-848b-ebced884a782	Zucchini Beef Casserole	2026-01-18 00:00:00	\N	Meal: Lunch; Prep time: 60 min	2026-01-18 00:00:00	American	{Regular,"Keto, Lunch"}	\N
12	caa5c832-49e2-4f72-af0c-6fb0560de084	Chicken Avocado Salad	2026-01-18 00:00:00	\N	Meal: Dinner; Prep time: 20 min	2026-01-18 00:00:00	American	{Regular,"Keto, Dinner"}	\N
13	d5cf1855-c87a-4cfa-8869-2c2141f0d831	Eggplant Lasagna	2026-01-18 00:00:00	\N	Meal: Dinner; Prep time: 60 min	2026-01-18 00:00:00	Italian	{Regular,"Keto, Dinner"}	\N
14	6e5eadd0-40ee-41c3-a731-a18a87aa683d	Salmon Spinach Alfredo	2026-01-18 00:00:00	\N	Meal: Dinner; Prep time: 60 min	2026-01-18 00:00:00	Italian	{Regular,"Keto, Dinner"}	\N
15	e262edc0-58b4-4e66-bf75-8dcfb8940768	Fish  Tacos	2026-01-18 00:00:00	\N	Meal: Lunch; Prep time: 60 min	2026-01-18 00:00:00	Mexican	{Regular,"Pesca, Lunch"}	\N
16	8ea7c280-409e-4ab3-a7be-1a94cbcfd553	Grilled fish Salad	2026-01-18 00:00:00	\N	Meal: Lunch; Prep time: 60 min	2026-01-18 00:00:00	American	{Regular,"Pesca, Lunch"}	\N
17	f92378fb-562d-44d4-8ecd-21f7f04690bb	Shrimp Rice Bowl	2026-01-18 00:00:00	\N	Meal: Lunch; Prep time: 60 min	2026-01-18 00:00:00	Asian Fusion	{Regular,"Pesca, Lunch"}	\N
18	bae7c3ba-97b5-4ecb-aaef-281eb02e11d9	Sushi Bowl	2026-01-18 00:00:00	\N	Meal: Lunch; Prep time: 60 min	2026-01-18 00:00:00	Japanese	{Regular,"Pesca, Lunch"}	\N
19	b8b9611f-0c54-4fb6-9998-d389e3cc9137	Tuna Sandwich	2026-01-18 00:00:00	\N	Meal: Lunch; Prep time: 60 min	2026-01-18 00:00:00	American	{Regular,"Pesca, Lunch"}	\N
20	eccf8f04-3d4d-44e9-920a-910c21ec5b6b	Shrimp Stirfry	2026-01-18 00:00:00	\N	Meal: Dinner; Prep time: 60 min	2026-01-18 00:00:00	Chinese	{Regular,"Pesca, Dinner"}	\N
21	f4cf189d-6c8f-40ee-b073-f76e2004a811	Tuna Stew	2026-01-18 00:00:00	\N	Meal: Dinner; Prep time: 60 min	2026-01-18 00:00:00	International	{Regular,"Pesca, Dinner"}	\N
22	13f1e913-8223-4335-8ef8-03a41322c453	Grilled Salmon	2026-01-18 00:00:00	\N	Meal: Dinner; Prep time: 60 min	2026-01-18 00:00:00	International	{Regular,"Pesca, Dinner"}	\N
23	4a3bd6e6-5176-4dfc-a536-80788b1e74fc	Shrimp Pasta	2026-01-18 00:00:00	\N	Meal: Dinner; Prep time: 60 min	2026-01-18 00:00:00	Italian	{Regular,"Pesca, Dinner"}	\N
24	87ec40b1-f5a4-48a6-86c9-99dd1314f87c	Smoked Salmon Toast	2026-01-18 00:00:00	\N	Meal: Breakfast; Prep time: 45 min	2026-01-18 00:00:00	American	{Regular,"Pesca, Breakfast"}	\N
25	db081df3-e337-4201-b50b-27dc56e5822f	Tuna Egg Bowl	2026-01-18 00:00:00	\N	Meal: Breakfast; Prep time: 60 min	2026-01-18 00:00:00	International	{Regular,"Pesca, Breakfast"}	\N
26	951ed036-0889-4686-b32c-844041671667	Shrimp Zucchini Stirfry	2026-01-18 00:00:00	\N	Meal: Lunch; Prep time: 60 min	2026-01-18 00:00:00	Chinese	{Regular,Pesca,"Keto, Lunch"}	\N
27	df249f8b-4331-4795-b78d-dc368e06e101	Avocado Tuna Salad	2026-01-18 00:00:00	\N	Meal: Lunch; Prep time: 60 min	2026-01-18 00:00:00	American	{Regular,Pesca,"Keto, Lunch"}	\N
28	18bf18b3-8db1-4cf0-b5f5-d382f9c575ef	Pesto Pasta	2026-01-18 00:00:00	\N	Meal: Lunch; Prep time: 60 min	2026-01-18 00:00:00	Italian	{Regular,"Vegetarian, Lunch"}	\N
29	62a94c5c-c216-48e0-9303-8f5aea52c97f	Stuffed Bell Pepper	2026-01-18 00:00:00	\N	Meal: Lunch; Prep time: 60 min	2026-01-18 00:00:00	American	{Regular,"Vegetarian, Lunch"}	\N
30	e667aaef-2fd7-4498-929b-5ddc32047c8a	Vegetable Risotto	2026-01-18 00:00:00	\N	Meal: Lunch; Prep time: 60 min	2026-01-18 00:00:00	Italian	{Regular,"Vegetarian, Lunch"}	\N
31	d3dcaf48-97e2-4359-a243-f97b028a4011	Vegetable Omelette	2026-01-18 00:00:00	\N	Meal: Dinner; Prep time: 20 min	2026-01-18 00:00:00	American	{Regular,"Vegetarian, Dinner"}	\N
32	979de4bb-0f73-4298-ba74-f8cc6f8b8440	Caprese Toast	2026-01-18 00:00:00	\N	Meal: Breakfast; Prep time: 20 min	2026-01-18 00:00:00	American	{Regular,"Vegetarian, Breakfast"}	\N
33	d7fef5c4-5610-4168-b5ca-5d8ba2568352	Cottage Cheese Bowl	2026-01-18 00:00:00	\N	Meal: Breakfast; Prep time: 20 min	2026-01-18 00:00:00	International	{Regular,"Vegetarian, Breakfast"}	\N
34	af5fbdad-14d1-4783-9115-f6ccaa0e6048	Egg and Avocado Toast	2026-01-18 00:00:00	\N	Meal: Breakfast; Prep time: 20 min	2026-01-18 00:00:00	American	{Regular,"Vegetarian, Breakfast"}	\N
35	8b3706f6-5521-400f-a58a-9202be44bc68	Honey and Banana Oatmeal	2026-01-18 00:00:00	\N	Meal: Breakfast; Prep time: 60 min	2026-01-18 00:00:00	American	{Regular,"Vegetarian, Breakfast"}	\N
36	25012321-bb1f-4bc7-9547-2ae2afe8e5f5	Peanut Butter Banana Smoothie	2026-01-18 00:00:00	\N	Meal: Breakfast; Prep time: 60 min	2026-01-18 00:00:00	American	{Regular,"Vegetarian, Breakfast"}	\N
37	22790b21-e98f-4769-968e-49cc41e32fd3	Quesadilla	2026-01-18 00:00:00	\N	Meal: Breakfast; Prep time: 20 min	2026-01-18 00:00:00	Mexican	{Regular,"Vegetarian, Breakfast"}	\N
38	f8e9d45b-e0ea-44cf-af13-fbab460ca3c8	Yogurt Parfait	2026-01-18 00:00:00	\N	Meal: Breakfast; Prep time: 60 min	2026-01-18 00:00:00	American	{Regular,"Vegetarian, Breakfast"}	\N
39	cb5670e8-7259-4b13-85d4-9f80fdc8ca77	Egg Muffins	2026-01-18 00:00:00	\N	Meal: Breakfast; Prep time: 60 min	2026-01-18 00:00:00	American	{Regular,Vegetarian,"Keto, Breakfast"}	\N
40	eaeddbec-85e1-475d-8c77-f74d6b0d5bcc	Keto Pancakes	2026-01-18 00:00:00	\N	Meal: Breakfast; Prep time: 60 min	2026-01-18 00:00:00	American	{Regular,Vegetarian,"Keto, Breakfast"}	\N
41	9dd8b141-01bb-48bc-bc45-d3194e366b2a	Lentil Salad	2026-01-18 00:00:00	\N	Meal: Lunch; Prep time: 60 min	2026-01-18 00:00:00	American	{Regular,Vegetarian,"Vegan, Lunch"}	\N
42	1e6ec417-ec19-4496-9f72-a654335389cd	Quinoa Bowl	2026-01-18 00:00:00	\N	Meal: Lunch; Prep time: 60 min	2026-01-18 00:00:00	International	{Regular,Vegetarian,"Vegan, Lunch"}	\N
43	a3d1ce1d-11c5-4564-96a8-f8f49f177751	Rice Vegetables	2026-01-18 00:00:00	\N	Meal: Lunch; Prep time: 60 min	2026-01-18 00:00:00	International	{Regular,Vegetarian,"Vegan, Lunch"}	\N
44	bf49a66a-2c0c-4264-96a8-157e77279717	Sweet Potato Bowl	2026-01-18 00:00:00	\N	Meal: Lunch; Prep time: 60 min	2026-01-18 00:00:00	International	{Regular,Vegetarian,"Vegan, Lunch"}	\N
45	68e0abba-fc2f-4d69-8db3-845db5c38937	Tofu Noodles	2026-01-18 00:00:00	\N	Meal: Lunch; Prep time: 45 min	2026-01-18 00:00:00	International	{Regular,Vegetarian,"Vegan, Lunch"}	\N
46	6ff4cc6c-9769-4e94-8dad-0d3d8444bc28	Veggie Wrap	2026-01-18 00:00:00	\N	Meal: Lunch; Prep time: 60 min	2026-01-18 00:00:00	American	{Regular,Vegetarian,"Vegan, Lunch"}	\N
47	1e3b88ec-9856-463d-a6b9-6787334eb7f2	Chickpea Curry	2026-01-18 00:00:00	\N	Meal: Dinner; Prep time: 60 min	2026-01-18 00:00:00	Indian	{Regular,Vegetarian,"Vegan, Dinner"}	\N
48	b8c8a042-d423-4339-837a-db560e7cd44c	Vegetable Soup	2026-01-18 00:00:00	\N	Meal: Dinner; Prep time: 60 min	2026-01-18 00:00:00	American	{Regular,Vegetarian,"Vegan, Dinner"}	\N
49	0e622fe3-b007-4ce6-baf3-9243ebbcc29b	Chia Pudding	2026-01-18 00:00:00	\N	Meal: Breakfast; Prep time: 20 min	2026-01-18 00:00:00	International	{Regular,Vegetarian,"Vegan, Breakfast"}	\N
50	fa9da63a-7271-4d78-8f97-4bf8261cb83c	Tofu Scramble	2026-01-18 00:00:00	\N	Meal: Breakfast; Prep time: 60 min	2026-01-18 00:00:00	International	{Regular,Vegetarian,"Vegan, Breakfast"}	\N
51	b63987a3-f18e-45eb-8866-0b4d23d732e3	Beef Burrito Bowl	2026-01-18 00:00:00	\N	Meal: Lunch; Prep time: 60 min	2026-01-18 00:00:00	Mexican	{Regular,Lunch}	\N
52	8e40c34c-b737-4235-a076-80c9c4f35478	Chicken Teriyaki Bowl	2026-01-18 00:00:00	\N	Meal: Lunch; Prep time: 60 min	2026-01-18 00:00:00	Japanese	{Regular,Lunch}	\N
53	ece998d2-ac0e-414f-b479-c41e5bc742f4	Turkey Chili	2026-01-18 00:00:00	\N	Meal: Dinner; Prep time: 60 min	2026-01-18 00:00:00	American	{Regular,Dinner}	\N
54	1d968ac3-6029-41e8-b852-9a5b3398d2e5	Chicken Fajitas	2026-01-18 00:00:00	\N	Meal: Dinner; Prep time: 45 min	2026-01-18 00:00:00	Mexican	{Regular,Dinner}	\N
55	31869365-a084-42b6-a3a4-1aa43bd9c954	Spaghetti Bolognese	2026-01-18 00:00:00	\N	Meal: Breakfast; Prep time: 60 min	2026-01-18 00:00:00	Italian	{Regular,Breakfast}	\N
56	29a733bc-b632-49aa-aabe-f113fc9c23cc	BBQ Chicken Sandwich	2026-01-18 00:00:00	\N	Meal: Breakfast; Prep time: 60 min	2026-01-18 00:00:00	American	{Regular,Breakfast}	\N
57	e26d5b27-38d5-44f2-be15-cd9cc369999c	Chicken Caesar Wrap	2026-01-18 00:00:00	\N	Meal: Lunch; Prep time: 60 min	2026-01-18 00:00:00	American	{Regular,Lunch}	\N
58	7a623184-a795-48c5-a392-17b553cca8fe	Beef Fried Rice	2026-01-18 00:00:00	\N	Meal: Lunch; Prep time: 60 min	2026-01-18 00:00:00	Chinese	{Regular,Lunch}	\N
59	f38dd98d-75c7-4399-96e4-350a7cb3ba20	Ham Omelette	2026-01-18 00:00:00	\N	Meal: Breakfast; Prep time: 20 min	2026-01-18 00:00:00	American	{Regular,Breakfast}	\N
60	58448138-f5c3-47ef-9862-b7652cc9f279	Chicken Pita Pocket	2026-01-18 00:00:00	\N	Meal: Lunch; Prep time: 60 min	2026-01-18 00:00:00	International	{Regular,Lunch}	\N
61	24f9f706-52b1-41f0-9a55-9f3a9fa1082d	Turkey Quinoa Bowl	2026-01-18 00:00:00	\N	Meal: Dinner; Prep time: 60 min	2026-01-18 00:00:00	International	{Regular,Dinner}	\N
62	01a5640a-b8b9-4592-a3d5-57160e7b0f48	Chicken Curry	2026-01-18 00:00:00	\N	Meal: Lunch; Prep time: 60 min	2026-01-18 00:00:00	Indian	{Regular,Lunch}	\N
63	2aa45194-120b-4082-9e1e-d150e3e003f1	Turkey Burger	2026-01-18 00:00:00	\N	Meal: Lunch; Prep time: 45 min	2026-01-18 00:00:00	American	{Regular,Lunch}	\N
64	59d99e3d-c80e-43a5-a4d3-08480ccefdc5	Chicken Noodle Soup	2026-01-18 00:00:00	\N	Meal: Dinner; Prep time: 60 min	2026-01-18 00:00:00	American	{Regular,Dinner}	\N
65	a6ad210a-7e18-4a33-ada3-0efdff88a097	Tuna Pasta Salad	2026-01-18 00:00:00	\N	Meal: Lunch; Prep time: 45 min	2026-01-18 00:00:00	Italian	{Regular,"Pesca, Lunch"}	\N
66	839acbc9-1f64-4450-ac65-31fcccd6f056	Shrimp Tacos	2026-01-18 00:00:00	\N	Meal: Lunch; Prep time: 60 min	2026-01-18 00:00:00	Mexican	{Regular,"Pesca, Lunch"}	\N
67	d7615a4c-d921-4be0-a3d5-781fb43cacba	Mushroom Pasta	2026-01-18 00:00:00	\N	Meal: Dinner; Prep time: 60 min	2026-01-18 00:00:00	Italian	{Regular,"Vegetarian, Dinner"}	\N
68	b8b50496-ae28-4c44-882a-016cc76bcd33	Vegetable Pizza	2026-01-18 00:00:00	\N	Meal: Lunch; Prep time: 60 min	2026-01-18 00:00:00	Italian	{Regular,"Vegetarian, Lunch"}	\N
69	d52a0471-2fc0-4512-9f8b-daf995a1a63f	Greek Salad	2026-01-18 00:00:00	\N	Meal: Lunch; Prep time: 60 min	2026-01-18 00:00:00	Greek	{Regular,"Vegetarian, Lunch"}	\N
70	9022719f-1472-4f42-ae21-839713cf3306	Chicken Tenders	2026-01-18 00:00:00	\N	Meal: Lunch; Prep time: 60 min	2026-01-18 00:00:00	American	{Regular,Lunch}	\N
71	bb99d489-37e4-49df-a3da-5d79ab3ef200	Spaghetti Carbonara	2026-01-18 00:00:00	\N	Meal: Lunch; Prep time: 60 min	2026-01-18 00:00:00	Italian	{Regular,Lunch}	\N
72	2ba4aa99-2510-4614-b946-03c06f83097c	Beef Lasagna	2026-01-18 00:00:00	\N	Meal: Dinner; Prep time: 60 min	2026-01-18 00:00:00	Italian	{Regular,Dinner}	\N
73	0bc2339b-82d8-4387-bc10-7898d7843eda	Arepa Reina Pepiada	2026-01-18 00:00:00	\N	Meal: Lunch; Prep time: 60 min	2026-01-18 00:00:00	Venezuelan	{Regular,Lunch}	\N
74	0dac6e8d-d6f6-45d4-9452-d762490561be	Enchiladas Verdes	2026-01-18 00:00:00	\N	Meal: Lunch; Prep time: 60 min	2026-01-18 00:00:00	Mexican	{Regular,Lunch}	\N
75	7807a193-3dfc-4bbb-b3cb-755ec087fbed	Chicken Shawarma	2026-01-18 00:00:00	\N	Meal: Lunch; Prep time: 60 min	2026-01-18 00:00:00	Middle Eastern	{Regular,Lunch}	\N
76	607ca6fb-fdf7-49fd-9893-4c1c3e292279	Ratatouille	2026-01-18 00:00:00	\N	Meal: Dinner; Prep time: 90 min	2026-01-18 00:00:00	French	{Regular,Vegeterian,"Vegan, Dinner"}	\N
77	37dfa5c3-2046-4186-9a92-1e9f174d6571	Cheeseburger	2026-01-18 00:00:00	\N	Meal: Lunch; Prep time: 60 min	2026-01-18 00:00:00	American	{Regular,Lunch}	\N
78	90ed506b-1e07-4977-b733-fe4319914771	Tacos al Pastor	2026-01-18 00:00:00	\N	Meal: Lunch; Prep time: 45 min	2026-01-18 00:00:00	Mexican	{Regular,Lunch}	\N
79	b0a6c10b-55f8-43e6-8959-7c42c46310dd	Mac and Cheese	2026-01-18 00:00:00	\N	Meal: Lunch; Prep time: 45 min	2026-01-18 00:00:00	American	{Regular,"Vegeterian, Lunch"}	\N
80	621537fb-a6d0-4256-9a3e-898c71b92738	Chimichurri Steak	2026-01-18 00:00:00	\N	Meal: Dinner; Prep time: 60 min	2026-01-18 00:00:00	Argentinian	{Regular,Dinner}	\N
81	77c512cc-2925-4330-9b77-5208f03dcca1	Peruvian Ceviche	2026-01-18 00:00:00	\N	Meal: Lunch; Prep time: 60 min	2026-01-18 00:00:00	Peruvian	{Regular,"Pesc, Lunch"}	\N
82	46120be1-c1d5-408f-a41e-bca40fe6d0c6	Fish and Chips	2026-01-18 00:00:00	\N	Meal: Lunch; Prep time: 60 min	2026-01-18 00:00:00	British	{Regular,"Pesc, Lunch"}	\N
83	c3d5a1d4-98cc-4cbf-b95c-b7284f13a216	Ramen Bowl	2026-01-18 00:00:00	\N	Meal: Dinner; Prep time: 60 min	2026-01-18 00:00:00	Japanese	{Regular,Dinner}	\N
84	c96f168c-9ef8-4a85-8699-1dea5e48538c	Mediterranean Lamb Kebabs	2026-01-18 00:00:00	\N	Meal: Dinner; Prep time: 60 min	2026-01-18 00:00:00	Mediterranean	{Regular,Dinner}	\N
85	901d6e08-30c5-49f9-8f61-d5c7e313780a	Creamy Spinach Gnocchi	2026-01-18 00:00:00	\N	Meal: Dinner; Prep time: 60 min	2026-01-18 00:00:00	Italian	{Regular,"Vegeterian, Dinner"}	\N
86	0d68f7ed-d902-4ce9-bc11-bc6f7361821f	Veggie Lasagna	2026-01-18 00:00:00	\N	Meal: Dinner; Prep time: 60 min	2026-01-18 00:00:00	Italian	{Regular,"Vegeterian, Dinner"}	\N
87	14b6194f-f474-4399-955d-a9baac425038	Ribeye Steak	2026-01-18 00:00:00	\N	Meal: Dinner; Prep time: 60 min	2026-01-18 00:00:00	American	{Regular,Dinner}	\N
88	28791816-09de-4373-bac3-731fc74739ad	Cordon Bleu Chicken	2026-01-18 00:00:00	\N	Meal: Dinner; Prep time: 60 min	2026-01-18 00:00:00	French	{Regular,Dinner}	\N
89	a91f657f-0f06-43e0-848a-d08fdd1a48ba	Almond Pancakes	2026-01-18 00:00:00	\N	Meal: Breakfast; Prep time: 60 min	2026-01-18 00:00:00	American	{Regular,"Vegetarian, Breakfast"}	\N
90	cba7a265-dbe4-4c78-9396-66b0a0393550	Broccoli Burgers	2026-01-18 00:00:00	\N	Meal: Lunch; Prep time: 60 min	2026-01-18 00:00:00	American	{Regular,"Vegetarian, Lunch"}	\N
91	80659c4d-41b4-480e-9744-ded78b3850c3	Vegan Chow Mein	2026-01-18 00:00:00	\N	Meal: Dinner; Prep time: 60 min	2026-01-18 00:00:00	Chinese	{Regular,Vegetarian,"Vegan, Dinner"}	\N
92	9f920199-a6a4-4544-9d47-a1376affc91f	Pasta and Bean Soup	2026-01-18 00:00:00	\N	Meal: Dinner; Prep time: 45 min	2026-01-18 00:00:00	Italian	{Regular,Vegetarian,"Vegan, Dinner"}	\N
93	643c7b99-7c25-4778-8009-c7a03b56c1e7	Borscht	2026-01-18 00:00:00	\N	Meal: Dinner; Prep time: 90 min	2026-01-18 00:00:00	Eastern European	{Regular,"Vegetarian, Dinner"}	\N
94	0f0ea799-e112-4945-bede-19400f0e276c	Moroccan Tagine	2026-01-18 00:00:00	\N	Meal: Dinner; Prep time: 60 min	2026-01-18 00:00:00	Moroccan	{Regular,Dinner}	\N
95	20a1fc1a-7a2d-444d-8023-5b899cdf6c9b	Kanda (Peanut Stew)	2026-01-18 00:00:00	\N	Meal: Dinner; Prep time: 60 min	2026-01-18 00:00:00	West African	{Regular,Dinner}	\N
96	d8853953-7375-41c4-bbf5-ad06d6e5e900	Venezuelan Empanadas	2026-01-18 00:00:00	\N	Meal: Lunch; Prep time: 60 min	2026-01-18 00:00:00	Venezuelan	{Regular,Lunch}	\N
97	ffb970a2-d7e3-4ad0-adf6-7e79718761c1	Argentinian Empanadas	2026-01-18 00:00:00	\N	Meal: Lunch; Prep time: 60 min	2026-01-18 00:00:00	Argentinian	{Regular,Lunch}	\N
98	57ea4903-6c88-4084-a962-f7925e4e4e57	Wagyu with Steak Sauce	2026-01-18 00:00:00	\N	Meal: Dinner; Prep time: 60 min	2026-01-18 00:00:00	American	{Regular,Dinner}	\N
99	cd128289-3c0d-43d8-b4da-00485be8c228	South African Curry and Rice	2026-01-18 00:00:00	\N	Meal: Lunch; Prep time: 90 min	2026-01-18 00:00:00	South African	{Regular,Lunch}	\N
100	fbbc1e46-afa3-47b0-8393-bdf0830067a9	Meatballs	2026-01-18 00:00:00	\N	Meal: Lunch; Prep time: 45 min	2026-01-18 00:00:00	Italian	{Regular,Lunch}	\N
\.


--
-- TOC entry 3738 (class 0 OID 0)
-- Dependencies: 335
-- Name: Ingredient_id_pk_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Ingredient_id_pk_seq"', 1, false);


--
-- TOC entry 3573 (class 2606 OID 17503)
-- Name: Ingredient Ingredient_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Ingredient"
    ADD CONSTRAINT "Ingredient_pkey" PRIMARY KEY (id_pk);


--
-- TOC entry 3571 (class 2606 OID 17536)
-- Name: recipe recipe_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.recipe
    ADD CONSTRAINT recipe_pkey PRIMARY KEY (id_pk);


--
-- TOC entry 3723 (class 0 OID 17493)
-- Dependencies: 334
-- Name: Ingredient; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE public."Ingredient" ENABLE ROW LEVEL SECURITY;

--
-- TOC entry 3722 (class 0 OID 17485)
-- Dependencies: 333
-- Name: recipe; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE public.recipe ENABLE ROW LEVEL SECURITY;

--
-- TOC entry 3734 (class 0 OID 0)
-- Dependencies: 80
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: pg_database_owner
--

GRANT USAGE ON SCHEMA public TO postgres;
GRANT USAGE ON SCHEMA public TO anon;
GRANT USAGE ON SCHEMA public TO authenticated;
GRANT USAGE ON SCHEMA public TO service_role;


--
-- TOC entry 3735 (class 0 OID 0)
-- Dependencies: 334
-- Name: TABLE "Ingredient"; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public."Ingredient" TO anon;
GRANT ALL ON TABLE public."Ingredient" TO authenticated;
GRANT ALL ON TABLE public."Ingredient" TO service_role;


--
-- TOC entry 3736 (class 0 OID 0)
-- Dependencies: 335
-- Name: SEQUENCE "Ingredient_id_pk_seq"; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public."Ingredient_id_pk_seq" TO anon;
GRANT ALL ON SEQUENCE public."Ingredient_id_pk_seq" TO authenticated;
GRANT ALL ON SEQUENCE public."Ingredient_id_pk_seq" TO service_role;


--
-- TOC entry 3737 (class 0 OID 0)
-- Dependencies: 333
-- Name: TABLE recipe; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.recipe TO anon;
GRANT ALL ON TABLE public.recipe TO authenticated;
GRANT ALL ON TABLE public.recipe TO service_role;


--
-- TOC entry 2374 (class 826 OID 16490)
-- Name: DEFAULT PRIVILEGES FOR SEQUENCES; Type: DEFAULT ACL; Schema: public; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON SEQUENCES TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON SEQUENCES TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON SEQUENCES TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON SEQUENCES TO service_role;


--
-- TOC entry 2375 (class 826 OID 16491)
-- Name: DEFAULT PRIVILEGES FOR SEQUENCES; Type: DEFAULT ACL; Schema: public; Owner: supabase_admin
--

ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON SEQUENCES TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON SEQUENCES TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON SEQUENCES TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON SEQUENCES TO service_role;


--
-- TOC entry 2373 (class 826 OID 16489)
-- Name: DEFAULT PRIVILEGES FOR FUNCTIONS; Type: DEFAULT ACL; Schema: public; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON FUNCTIONS TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON FUNCTIONS TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON FUNCTIONS TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON FUNCTIONS TO service_role;


--
-- TOC entry 2377 (class 826 OID 16493)
-- Name: DEFAULT PRIVILEGES FOR FUNCTIONS; Type: DEFAULT ACL; Schema: public; Owner: supabase_admin
--

ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON FUNCTIONS TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON FUNCTIONS TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON FUNCTIONS TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON FUNCTIONS TO service_role;


--
-- TOC entry 2372 (class 826 OID 16488)
-- Name: DEFAULT PRIVILEGES FOR TABLES; Type: DEFAULT ACL; Schema: public; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON TABLES TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON TABLES TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON TABLES TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON TABLES TO service_role;


--
-- TOC entry 2376 (class 826 OID 16492)
-- Name: DEFAULT PRIVILEGES FOR TABLES; Type: DEFAULT ACL; Schema: public; Owner: supabase_admin
--

ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON TABLES TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON TABLES TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON TABLES TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON TABLES TO service_role;


-- Completed on 2026-03-16 22:15:04

--
-- PostgreSQL database dump complete
--

