# Generated by Django 5.2.12 on 2026-04-08 03:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipes', '0008_recipe_ix_recipe_creator_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MealPlanEntry',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('meal_slot', models.CharField(choices=[('breakfast', 'Breakfast'), ('snack1', 'Snack 1'), ('lunch', 'Lunch'), ('snack2', 'Snack 2'), ('dinner', 'Dinner')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_plan_entries', to='recipes.recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_plan_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Meal Plan Entry',
                'verbose_name_plural': 'Meal Plan Entries',
                'db_table': 'meal_plan_entries',
                'ordering': ['date', 'meal_slot'],
                'indexes': [models.Index(fields=['user', 'date'], name='ix_mealplan_user_date')],
                'constraints': [models.UniqueConstraint(fields=('user', 'date', 'meal_slot'), name='uq_mealplan_user_date_slot')],
            },
        ),
    ]
