# Generated by Django 5.2.10 on 2026-01-30 04:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TriedRecipe',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('recipe_id', models.PositiveBigIntegerField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tried Recipe',
                'verbose_name_plural': 'Tried Recipes',
                'db_table': 'tried_recipes',
                'ordering': ['-date_added'],
            },
        ),
    ]
