# Generated by Django 5.2.10 on 2026-01-30 04:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('social', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='triedrecipe',
            name='tried_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tried_recipes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='triedrecipe',
            unique_together={('tried_by', 'recipe_id')},
        ),
    ]
