# Generated by Django 5.2.12 on 2026-03-23 03:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_cookbook_cookbookrecipe_cookbook_ix_cookbook_owner_and_more'),
        ('social', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('privacy', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeLike',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Recipe Like',
                'verbose_name_plural': 'Recipe Likes',
                'db_table': 'recipe_likes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecipeReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=250)),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Recipe Review',
                'verbose_name_plural': 'Recipe Reviews',
                'db_table': 'recipe_reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user_block',
            },
        ),
        migrations.CreateModel(
            name='UserFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user_follows',
            },
        ),
        migrations.AlterUniqueTogether(
            name='triedrecipe',
            unique_together=set(),
        ),
        # Remove the old plain-integer recipe_id column before adding the proper
        # recipe FK (which Django also maps to a recipe_id column). The DB already
        # has recipe_id from migration 0001, so it must be dropped first.
        migrations.RemoveField(
            model_name='triedrecipe',
            name='recipe_id',
        ),
        migrations.AddField(
            model_name='triedrecipe',
            name='recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tried_entries', to='recipes.recipe'),
        ),
        migrations.AddConstraint(
            model_name='triedrecipe',
            constraint=models.UniqueConstraint(fields=('tried_by', 'recipe'), name='uq_triedrecipe_user_recipe'),
        ),
        migrations.AddField(
            model_name='postrecipe',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_recipe', to='recipes.recipe'),
        ),
        migrations.AddField(
            model_name='recipelike',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_likes', to='recipes.recipe'),
        ),
        migrations.AddField(
            model_name='recipelike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_recipes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recipereview',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='written_recipe_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recipereview',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_reviews', to='recipes.recipe'),
        ),
        migrations.AddField(
            model_name='userblock',
            name='blocked',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_edges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userblock',
            name='blocker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocking_edges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userfollow',
            name='followee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower_edges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userfollow',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_edges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='recipelike',
            index=models.Index(fields=['user'], name='ix_recipelike_user'),
        ),
        migrations.AddIndex(
            model_name='recipelike',
            index=models.Index(fields=['recipe'], name='ix_recipelike_recipe'),
        ),
        migrations.AddIndex(
            model_name='recipelike',
            index=models.Index(fields=['created_at'], name='ix_recipelike_created_at'),
        ),
        migrations.AddConstraint(
            model_name='recipelike',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='uq_recipelike_user_recipe'),
        ),
        migrations.AddConstraint(
            model_name='recipereview',
            constraint=models.UniqueConstraint(fields=('author', 'recipe'), name='uq_recipereview_author_recipe'),
        ),
        migrations.AddIndex(
            model_name='userblock',
            index=models.Index(fields=['blocker'], name='ix_userblock_blocker'),
        ),
        migrations.AddIndex(
            model_name='userblock',
            index=models.Index(fields=['blocked'], name='ix_userblock_blocked'),
        ),
        migrations.AddIndex(
            model_name='userblock',
            index=models.Index(fields=['created_at'], name='ix_userblock_created_at'),
        ),
        migrations.AddConstraint(
            model_name='userblock',
            constraint=models.UniqueConstraint(fields=('blocker', 'blocked'), name='uq_userblock_blocker_blocked'),
        ),
        migrations.AddConstraint(
            model_name='userblock',
            constraint=models.CheckConstraint(condition=models.Q(('blocker', models.F('blocked')), _negated=True), name='ck_userblock_no_self_block'),
        ),
        migrations.AddIndex(
            model_name='userfollow',
            index=models.Index(fields=['follower'], name='ix_userfollow_follower'),
        ),
        migrations.AddIndex(
            model_name='userfollow',
            index=models.Index(fields=['followee'], name='ix_userfollow_followee'),
        ),
        migrations.AddIndex(
            model_name='userfollow',
            index=models.Index(fields=['created_at'], name='ix_userfollow_created_at'),
        ),
        migrations.AddConstraint(
            model_name='userfollow',
            constraint=models.UniqueConstraint(fields=('follower', 'followee'), name='uq_userfollow_follower_followee'),
        ),
        migrations.AddConstraint(
            model_name='userfollow',
            constraint=models.CheckConstraint(condition=models.Q(('follower', models.F('followee')), _negated=True), name='ck_userfollow_no_self_follow'),
        ),
    ]
