# Generated by Django 5.2.10 on 2026-01-30 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('daily_calorie_goal', models.SmallIntegerField(null=True)),
                ('daily_protein_goal', models.SmallIntegerField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('bio', models.CharField(blank=True, default='', max_length=500)),
                ('diet_type', models.JSONField(blank=True, default=dict)),
                ('profile_picture', models.URLField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'db_table': 'user_profiles',
            },
        ),
    ]
