# Generated by Django 5.2.12 on 2026-04-08 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='daily_carbs_goal',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='daily_fat_goal',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
