# Generated by Django 5.2.13 on 2026-04-09 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_userprofile_daily_carbs_goal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='allergies',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_onboarded',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
