# Generated by Django 5.2.13 on 2026-04-09 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_userprofile_is_onboarded_allergies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='diet_type',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
