# Generated by Django 5.2.12 on 2026-03-23 03:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_remove_recipe_intstructions_recipe_creator_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cookbook',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cookbooks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cookbook',
                'verbose_name_plural': 'Cookbooks',
                'db_table': 'cookbooks',
                'ordering': ['-date_updated'],
            },
        ),
        migrations.CreateModel(
            name='CookbookRecipe',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('cookbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cookbook_recipes', to='recipes.cookbook')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_cookbooks', to='recipes.recipe')),
            ],
            options={
                'verbose_name': 'Cookbook Recipe',
                'verbose_name_plural': 'Cookbook Recipes',
                'db_table': 'cookbook_recipes',
                'ordering': ['-date_added'],
            },
        ),
        migrations.AddIndex(
            model_name='cookbook',
            index=models.Index(fields=['owner'], name='ix_cookbook_owner'),
        ),
        migrations.AddIndex(
            model_name='cookbook',
            index=models.Index(fields=['date_updated'], name='ix_cookbook_date_updated'),
        ),
        migrations.AddConstraint(
            model_name='cookbook',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='uq_cookbook_owner_name'),
        ),
        migrations.AddIndex(
            model_name='cookbookrecipe',
            index=models.Index(fields=['cookbook'], name='ix_cookbookrecipe_cookbook'),
        ),
        migrations.AddIndex(
            model_name='cookbookrecipe',
            index=models.Index(fields=['recipe'], name='ix_cookbookrecipe_recipe'),
        ),
        migrations.AddConstraint(
            model_name='cookbookrecipe',
            constraint=models.UniqueConstraint(fields=('cookbook', 'recipe'), name='uq_cookbookrecipe_cookbook_recipe'),
        ),
    ]
