# Generated by Django 5.2.12 on 2026-03-23 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_cookbook_cookbookrecipe_cookbook_ix_cookbook_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cookbook',
            name='description',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
