# Generated by Django 5.2.12 on 2026-04-02 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_fix_recipe_field_lengths'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='measure_type',
            field=models.CharField(choices=[('grams', 'Grams'), ('cups', 'Cups'), ('tablespoons', 'Tablespoons')], default='grams', max_length=12),
        ),
    ]
