# Generated by Django 5.2.12 on 2026-04-05 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_recipe_measure_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image_1',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='recipe',
            name='image_2',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='recipe',
            name='image_3',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
