# Generated by Django 5.2.12 on 2026-04-06 02:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0004_alter_ingredient_calories_per_100g_and_more'),
        ('recipes', '0007_recipe_image_1_recipe_image_2_recipe_image_3'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['creator'], name='ix_recipe_creator'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['-date_created'], name='ix_recipe_date_created'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['cuisine_type'], name='ix_recipe_cuisine_type'),
        ),
        migrations.AddIndex(
            model_name='recipeingredient',
            index=models.Index(fields=['recipe', 'ingredient'], name='ix_ri_recipe_ingredient'),
        ),
    ]
